version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build


hooks:
  BeforeInstall:
    - location: backup.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: chmod.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: deploy.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: switch.sh
      timeout: 180
      runas: root