version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/


hooks:
  BeforeInstall:
    - location: clean.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: chmod.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: deploy.sh
      timeout: 180
      runas: root