version: 0.2

phases:
  install:
    runtime-version:
      java: corretto17
  build:
    commands:
      - echo Phase/build Start
      - gradle wrapper
      - ls
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
