version: 0.2

phases:
  install:
    runtime-version:
      java: corretto17
    commands:
      - apt update
      - apt install -y net-tools
      - aws ecr-public get-login-password --region $MY_REGION | docker login --username AWS --password-stdin $MY_ECR_URL
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin docker.io
  build:
    commands:
      - echo Phase/build Start
      - gradle wrapper
      - chmod +x ./gradlew
      - ./gradlew build
      - docker build -t $MY_ECR_REPOSITORY_NAME:latest .
      - docker tag $MY_ECR_REPOSITORY_NAME:latest $MY_ECR_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $MY_ECR_URI:latest

artifacts:
  files:
    - scripts/deploy.sh
    - scripts/clean.sh
    - appspec.yml
    - docker-compose.yml
  discard-paths: yes
