version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/app/nginx/default:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/app/nginx/service-url.inc:/etc/nginx/service-url.inc
    networks:
      - backend
  app1:
    image: ${ECR_IMAGE}
    ports:
      - ${PORT1}:${PORT1}
      - ${JMX_PORT1}:${JMX_PORT1}
    environment:
      - IDLE_PORT=${PORT1}
      - JAVA_RMI_SERVER_HOSTNAME=${HOST_IP}
      - JMX_PORT=${JMX_PORT1}
    volumes:
      - /home/ubuntu/app/config:/home/ubuntu/app/config
    networks:
      - backend
  app2:
    image: ${ECR_IMAGE}
    ports:
      - ${PORT2}:${PORT2}
      - ${JMX_PORT2}:${JMX_PORT2}
    environment:
      - IDLE_PORT=${PORT2}
      - JAVA_RMI_SERVER_HOSTNAME=${HOST_IP}
      - JMX_PORT=${JMX_PORT2}
    volumes:
      - /home/ubuntu/app/config:/home/ubuntu/app/config
    networks:
      - backend
  proxysql:
    image: proxysql/proxysql:2.1.0
    container_name: proxysql
    hostname: proxysql
    ports:
      - "6032:6032"
      - "6033:6033"
    volumes:
      - "/home/ubuntu/app/proxysql/data:/var/lib/proxysql"
      - "/home/ubuntu/app/proxysql/conf/proxysql.cnf:/etc/proxysql.cnf"
    networks:
      - backend
networks:
  backend: