spring:
  # DB Datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/my_code_review?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
  # Spring Data JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  # Redis cache layer 설정
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

# 로그 레벨 설정
logging:
  level:
    org.springframework: info
    org.springframework.security: trace
    web: debug

# jwt secret key
com:
  web:
    jwt:
      secret: hello


# scheme, host, port
app:
  domain:
    scheme: http
    host: localhost
    port: 3000
