spring:
  profiles:
    active: local
    group:
      local:
        - oauth
      prod:
        - oauth
      test:
        - oauth

---
spring:
  config:
    activate:
      on-profile: oauth

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: test
