spring:
  datasource:
    url: jdbc:h2:mem:~/MyCodeReviewApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Redis cache layer 설정
  data:
    redis:
      host: localhost
      port: 6380
  cache:
    type: redis
  # jmx
  jmx:
    enabled: true

# 스프링 부트 액추에이터
management:
  endpoints:
    enabled-by-default: false # 모두 비활성화
  endpoint:
    health:
      enabled: true # health check 활성화
    info:
      enabled: # info 조회 활성화

com:
  web:
    jwt:
      secret: testKey

app:
  domain:
    scheme: http
    host: localhost
    port: 3000